# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gee < Formula
  desc "Efficiently Manage Multiple Git Repositories."
  homepage "https://github.com/stcrestrada/gee"
  version "2.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stcrestrada/gee/releases/download/v2.4.0/gee_2.4.0_darwin_amd64.tar.gz"
      sha256 "c675a9f05b011b72e40d8b56af5681553cfdb3b2e5c9cea543f4a2a1edb1a7cd"

      define_method(:install) do
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stcrestrada/gee/releases/download/v2.4.0/gee_2.4.0_darwin_arm64.tar.gz"
      sha256 "977b17122f25ba47983a0caf941607aee6db8ea24bfb20cdfbdf13b51b12a492"

      define_method(:install) do
        bin.install "gee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stcrestrada/gee/releases/download/v2.4.0/gee_2.4.0_linux_amd64.tar.gz"
      sha256 "624e4fbb74e9bba4a09856a821ca76bddbd6b14115a0630e66b53003ab1f20df"
      define_method(:install) do
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stcrestrada/gee/releases/download/v2.4.0/gee_2.4.0_linux_arm64.tar.gz"
      sha256 "27c258cab7ef542c65582263ed5fb55033636356fc012d40579eb06968344254"
      define_method(:install) do
        bin.install "gee"
      end
    end
  end
end
