# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gee < Formula
  desc "Efficiently Manage Multiple Git Repositories."
  homepage "https://github.com/stcrestrada/gee"
  version "2.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stcrestrada/gee/releases/download/v2.4.1/gee_2.4.1_darwin_amd64.tar.gz"
      sha256 "91f027f2ece980eb75b573908992280af288b6327553ad11971ce21f4d22b152"

      define_method(:install) do
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stcrestrada/gee/releases/download/v2.4.1/gee_2.4.1_darwin_arm64.tar.gz"
      sha256 "be0255916c0099c20202b0fb3a8e8ff2e663e82b8d688a7e94c39c80f3365d2d"

      define_method(:install) do
        bin.install "gee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stcrestrada/gee/releases/download/v2.4.1/gee_2.4.1_linux_amd64.tar.gz"
      sha256 "d14b823c28b68c6e42efca4a8d65aac90ad2e3a42186a7ecfad87ebb7df23e5b"
      define_method(:install) do
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stcrestrada/gee/releases/download/v2.4.1/gee_2.4.1_linux_arm64.tar.gz"
      sha256 "720b95b6f9e81ef719cd0fb7ea1c5a916f695be885437a7b75ee794e1a3dbe59"
      define_method(:install) do
        bin.install "gee"
      end
    end
  end
end
