# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gee < Formula
  desc "Efficiently Manage Multiple Git Repositories."
  homepage "https://github.com/stcrestrada/gee"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stcrestrada/gee/releases/download/v2.3.0/gee_2.3.0_darwin_amd64.tar.gz"
      sha256 "35192ee44fca5938166fb2cd3e7210f9501a91f0952f9177f780ad2c15413cff"

      define_method(:install) do
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stcrestrada/gee/releases/download/v2.3.0/gee_2.3.0_darwin_arm64.tar.gz"
      sha256 "57437fc925866125cdd8924da95eb4424ff8be20312a9f58cdb6abbfaf752ea8"

      define_method(:install) do
        bin.install "gee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stcrestrada/gee/releases/download/v2.3.0/gee_2.3.0_linux_amd64.tar.gz"
      sha256 "8d3a34a55affcd3e53164f32869703480993bb5b8180665468db91941ab17ec9"
      define_method(:install) do
        bin.install "gee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stcrestrada/gee/releases/download/v2.3.0/gee_2.3.0_linux_arm64.tar.gz"
      sha256 "78a440757b8f7a36086ca12a6a104281a1059d171b468df9fc3e7a618c999cf9"
      define_method(:install) do
        bin.install "gee"
      end
    end
  end
end
